### ISSUE TITLE
FAB should move when toasts are active

### ISSUE THREAD

**Issue by brandonrosage** [ushahidi/platform-mobile#66] opened 2017-02-24 17:21 UTC
I'm not sure what the deal is with Ionic here, but when a toast is displayed on a screen with a FAB, that button should move up and not obscure the content of the toast.

It both obscures the toast and makes it nearly impossible to read or tap the appended action (e.g. "Clear"):

![toast bug](https://cloud.githubusercontent.com/assets/1136279/23313380/10ca3e6c-fa83-11e6-8867-3533646ecdba.png)

[Google demonstrates the intended interaction](https://storage.googleapis.com/material-design/publish/material_v_10/assets/0B6Okdz75tqQsNkd0RU1LNktBdUk/components_snackbar_usage_fabdo_005.mp4).

**Comment by dalezak** [comment] 2017-02-24 18:14
Ooohh, this was working before, I'll investigate why it stopped working...

**Comment by dalezak** [comment] 2017-02-24 22:18
Looks like the issue is related to https://github.com/angular/angular/issues/5415, the BasePage is defining the `@ViewChild(Content)` which is not being set in subclasses 😢

**Comment by dalezak** [comment] 2017-02-24 23:14
Looks like this issue might be fixed in Angular 2.3.0, but will have to wait until Ionic2 is updated to use it. In the meantime, I've added `@ViewChild(Content)` to all the pages since its not being populated from the BasePage.

**Comment by dalezak** [comment] 2017-02-24 23:15
Fixed for now.. closing issue.

**Closed by dalezak** 2017-02-24 23:15 UTC
