### ISSUE TITLE
Android App breaks when user is logged in to a deployment

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform-mobile#98] opened 2017-03-28 14:11 UTC
Feedback from user on intercom having trouble using the mobile apps while signed in.

* All the surveys disappear off the list, and the option to submit is greyed out
*Logging out does not bring that back up, I uninstall the App and reinstall it
*We were looking to use it as a basis for a mapping workshop, but we might have a bit of difficulty with the app so early

**Comment by dalezak** [comment] 2017-03-28 14:42
Hmm, @aoduor do you know which deployment they were trying to log into? Were they having issues with the iOS or Android app?

**Comment by Gerw88** [comment] 2017-03-28 18:11
@dalezak should I message you my deployment? I don't think it had a bearing, I tried another with the same problem. @aoduor has described it above. I am on the Android app v1.1

**Comment by dalezak** [comment] 2017-03-29 16:47
@Gerw88 Curious, if you pull down to refresh on the deployment details screen, after logging in, do the Forms show up?

I tested the Android version on https://dale.ushahidi.io, and was able to login fine. Can you send me your deployment to test?

**Comment by Gerw88** [comment] 2017-03-29 22:55
I have emailed you the details of my deployment - there is just one survey at the moment. You should have admin access now. The deployment still works as expected on the web. Published/Unpublished points appear as expected. And so on.

On the mobile app, the app works well - everything you would expect, just using it as an un-logged-in user. However, after logging in surveys within the deployment disappear, and do not reappear on logging out. (Sorry, I am not able to be more specific). Refreshing doesn't do anything - the list "finishes" refreshing (as in the animation stops), and nothing changes. Also responses added when logged in don't appear for approval or on the map. Logging out does not fix these issues.

**Comment by dalezak** [comment] 2017-03-30 00:34
@Gerw88 I found the cause of the issue, turns out it was being caused by `Promise.all`.

Although it returns results in the correct order, it does not guarantee they are executed in order.

In most cases this isn't an issue, but on this view the `loadDeployment` was occasionally happening after `loadForms` and overriding the Forms.

I'm just testing a solution, once I have it ready I'll share a new APK with you to test on your deployment.

**Comment by dalezak** [comment] 2017-03-30 17:20
Good news @Gerw88, I've fixed the problem, will be available in 1.2 update.

Closing issue.

**Closed** 2017-03-30 17:26 UTC
Labels: P0: Unbreak now!, ready
